export const CTX_REDUCE_LIGHT_DESCRIPTION = `Stamp an item as no longer needed for the work ahead. Not a delete: stamping QUEUES it, the item stays readable until Magic Context clears stamped items in one sweep, newest tags are protected, and a cleared item goes to the archive (recent: a [dropped §N§] placeholder; older: removed) recoverable via ctx_expand(message=N). The question is "does this need to stay on my desk for what comes next?" — a file you keep editing stays, the grep that found it goes. Stamp used reads/searches/outputs, acted-on build/test output, redundant dumps, extracted pasted payloads; keep user messages, your own text, unresolved errors, raw evidence, exact wording that may matter. Look at each tag; never blanket-stamp "1-50". Grammar: "3-5", "1,2,9", "1-5,8,12-15".`;

export const CTX_EXPAND_LIGHT_DESCRIPTION = `Recover raw conversation behind a <session-history> heading or around a ctx_search hit: ctx_expand(start, end) returns [N] U:/A: lines (~15K-token cap; oversized ranges return the head and where to continue). verbose=true lists messages with per-part previews to pick one; message=N returns that message in full, including a tool output released with ctx_reduce. Ranges after the last compartment are your live tail, not expandable.`;

export const CTX_NOTE_LIGHT_DESCRIPTION = `Session notes: information you have now, attached to work you are deliberately not doing now (findings, a decision with its reasons, a backlog item with evidence; "take a note" from the user always qualifies). Not the next few steps, a plan you are executing, or restart/fold insurance; durable facts are ctx_memory; if the detail lives in a file, carry the path, not a copy. First line = title (<80 chars). write saves; read lists \`#id · age · title\` rows (note_ids for bodies); update changes one (note_ids=[N]); dismiss retires 1–50. surface_condition parks the note until the system confirms it against repo files, git, GitHub or the web (never this conversation), then returns it as ready.`;

export const CTX_MEMORY_LIGHT_DESCRIPTION = `Durable facts about this project, shared with every agent on it and kept for the months this work lasts; active ones are already in <project-memory> as \`#id: fact\`. Write one standalone fact when it must not have to be found again — a rule, an architecture fact, a constraint, a config value, a naming convention — especially what cost you turns. A pending intention with evidence is ctx_note, not memory. write (content + category); update one id (content; category optional); archive one or more ids (reason optional); merge two or more ids (content); get 1–20 ids in any status.`;

export const CTX_SEARCH_LIGHT_DESCRIPTION = `Search the archive — everything that ever happened here that is not on your desk: memories not in <project-memory>, compacted conversation, commits, notes. Phrase query as a natural-language question carrying the exact terms you expect ("where is the opencode source code path?", "why did we choose SQLite over postgres?", "how does the dreamer lease work?") — a keyword stack finds less. Sources (omit for all): memory (rules, conventions), message (compacted conversation; hits carry ordinals for ctx_expand), git_commit (when did this change), note (parked follow-ups). Memory ids alone (\`#7234\`) resolve directly. from/to restrict every source to an inclusive UTC date range.`;
